// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OPTriviaAPI.Data;

#nullable disable

namespace OPTriviaAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OPTriviaAPI.Trivia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trivias");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Text = "Luffy is based on the Hindu god Hanuman"
                        },
                        new
                        {
                            Id = -2,
                            Text = "Each member of the Straw Hat Crew is based after a mythological demon from various cultures"
                        },
                        new
                        {
                            Id = -3,
                            Text = "Oda is a madman"
                        },
                        new
                        {
                            Id = -4,
                            Text = "Blackbeard is directly based on Davy Jones, both the real figure and the mythological one"
                        },
                        new
                        {
                            Id = -5,
                            Text = "Klaubaterman are actually a real-life mythical creature, which are accurately represented in the OP universe"
                        },
                        new
                        {
                            Id = -6,
                            Text = "The Library of Ohara had a number of books on culture, rather than just research material (see Brag Men)"
                        },
                        new
                        {
                            Id = -7,
                            Text = "The in-universe book Brag Men was first seen at Ohara, before being brought up by Nami.  It is now an IRL One Piece themed Gym for working out."
                        },
                        new
                        {
                            Id = -8,
                            Text = "Ace was not originally written to be Roger's son"
                        },
                        new
                        {
                            Id = -9,
                            Text = "There is no such thing as a Logia fruit (shameless self promotion, OPTreasureTree)"
                        },
                        new
                        {
                            Id = -10,
                            Text = "One Piece has mythological references from Norse, Greco-Roman, Japanese, and Hindu mythologies/religions"
                        },
                        new
                        {
                            Id = -11,
                            Text = "The new Monster Trio post-Wano arc represents the Trinity of the Planes, which is also represented by the Ancient Weapons"
                        },
                        new
                        {
                            Id = -12,
                            Text = "A more direct translation of Gorusei means '5 elder planets', not '5 elder stars'"
                        },
                        new
                        {
                            Id = -13,
                            Text = "It's been over 800 years since I last heard them, the Drums of Liberation.  JOY BOY!"
                        },
                        new
                        {
                            Id = -14,
                            Text = "If Luffy was born somewhere IRL, Oda claims it would be Brazil"
                        },
                        new
                        {
                            Id = -15,
                            Text = "Luffy is based after old-timey rubber-hose cartoon characters"
                        },
                        new
                        {
                            Id = -16,
                            Text = "One Piece is an ode to childhood joy"
                        },
                        new
                        {
                            Id = -17,
                            Text = "Oda foreshadows future events years in advance, if you go back and reread chapters"
                        },
                        new
                        {
                            Id = -18,
                            Text = "The Drums of Liberation have yet to be accurately shown in the Anime to date, as Oda writes it as 4 beats instead of the 3-beat Skypeia version."
                        },
                        new
                        {
                            Id = -19,
                            Text = "There is an amazing cover story featuring Enel on the Moon that has yet to be animated in any regard, giving context to Lunar Civilizations years before the introduction of Lunarians"
                        },
                        new
                        {
                            Id = -20,
                            Text = "It is very likely that Shanks was to give Ace the Gum Gum fruit based on his relation to Roger and a specific cover-page, where Ace looks like a certain important future character"
                        },
                        new
                        {
                            Id = -21,
                            Text = "Buggy deserves every bit of praise he gets, and is very likely another mythical zoan"
                        },
                        new
                        {
                            Id = -22,
                            Text = "Oda often forgets about certain plotlines, and has admitted to going to fan sites to show him what plotlines he hasn't gone through yet"
                        },
                        new
                        {
                            Id = -23,
                            Text = "Please hire me"
                        },
                        new
                        {
                            Id = -24,
                            Text = "Oda often puts unimportant or unnecessary information in SBS volumes released in Japan, Q and A format.  These often contain clues towards the main story in terms of things we haven't explored yet"
                        },
                        new
                        {
                            Id = -25,
                            Text = "According to both Whitebeard and Howard Hamlin, of Hamlin Hamlin & McGill, the One Piece, the One Piece is Real!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
